# Generated by Django 5.2.8 on 2025-12-02 11:56

import chama.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chama_code', models.CharField(default=chama.models.generate_unique_code, editable=False, max_length=10, unique=True)),
                ('chama_type', models.CharField(choices=[('savings', 'Savings Group'), ('lending', 'Lending Group'), ('merry', 'Merry-Go-Round')], default='savings', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin/Treasurer'), ('member', 'Member')], default='member', max_length=10)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chama.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chamagroup',
            name='members',
            field=models.ManyToManyField(through='chama.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
