# Generated by Django 5.2.8 on 2025-12-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved (Disbursed)'), ('rejected', 'Rejected'), ('paid', 'Fully Paid')], default='pending', max_length=20)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chama.membership')),
            ],
        ),
    ]
