# Generated by Django 5.2.8 on 2025-12-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamagroup',
            name='pot_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='membership',
            name='has_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
