# Generated by Django 5.2.8 on 2025-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0004_chamagroup_pot_balance_membership_has_eaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamagroup',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
