# Generated by Django 5.2.8 on 2025-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0005_chamagroup_contribution_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
