# Generated by Django 5.2.8 on 2025-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0006_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamagroup',
            name='contribution_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chamagroup',
            name='late_penalty_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
