# Generated by Django 5.2.8 on 2025-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0007_chamagroup_contribution_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamagroup',
            name='goal_name',
            field=models.CharField(blank=True, help_text='e.g. Buy Land', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamagroup',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target amount to save', max_digits=12),
        ),
    ]
