# Generated by Django 5.2.8 on 2025-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0008_chamagroup_goal_name_chamagroup_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='goal_name',
            field=models.CharField(blank=True, help_text='e.g. Buy Land', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
